import { Injectable, computed, inject, signal } from '@angular/core';
import { SafeStorageService } from './safe-storage';

export type AppLanguage = 'en' | 'fr';

type TranslationParams = Record<string, string | number>;

const STORAGE_KEY = 'innovacare_language';

const TRANSLATIONS: Record<AppLanguage, Record<string, string>> = {
  en: {
    'language.english': 'EN',
    'language.french': 'FR',
    'public.nav.home': 'Home',
    'public.nav.solutions': 'Solutions',
    'public.nav.industries': 'Industries',
    'public.nav.catalogue': 'Catalogue',
    'public.nav.pricing': 'Pricing',
    'public.nav.ordre': 'Ordre Professionnel',
    'public.nav.verify': 'Verify Membership',
    'public.nav.faq': 'FAQ',
    'public.nav.login': 'Sign in',
    'public.nav.demo': 'Book a demo',
    'public.nav.language': 'Language',
    'shell.menuToggle': 'Toggle menu',
    'shell.roleLearner': 'Learner',
    'shell.profile': 'Profile',
    'shell.logout': 'Logout',
    'shell.primaryNav': 'Primary',
    'shell.overview': 'Overview',
    'shell.resources': 'Resources',
    'shell.dashboard': 'Dashboard',
    'shell.assignments': 'Assignments',
    'shell.woundLibrary': 'Quick Practice Zone',
    'shell.profileLink': 'Your Profile',
    'shell.policies': 'Policies and Procedures',
    'shell.certifications': 'Certifications',
    'shell.officialCertifications': 'Official Certifications',
    'shell.onsiteExams': 'Onsite Exams',
    'shell.verifyMember': 'Verify Membership',
    'assignments.title': 'My Assignments',
    'assignments.subtitle': 'Your assigned training, sorted by what needs attention first.',
    'assignments.searchPlaceholder': 'Search courses…',
    'assignments.sortBy': 'Sort by',
    'assignments.sortDue': 'Due date',
    'assignments.sortAz': 'Title (A–Z)',
    'assignments.sortKind': 'Type',
    'assignments.tabActive': 'Active',
    'assignments.tabCompleted': 'Completed',
    'assignments.statActive': 'Active',
    'assignments.statOverdue': 'Overdue',
    'assignments.statCompleted': 'Completed',
    'assignments.emptyActive': 'No active assignments — you are all caught up! 🎉',
    'assignments.emptyCompleted': 'No completed courses yet.',
    'assignments.start': 'Start',
    'assignments.resume': 'Resume',
    'assignments.review': 'Review',
    'assignments.addToCalendar': 'Add to calendar',
    'assignments.googleCalendar': 'Google Calendar',
    'assignments.downloadIcs': 'Download .ics (Outlook/Apple)',
    'assignments.noDueDate': 'No due date',
    'assignments.overdue': 'Overdue',
    'assignments.dueOn': 'Due {date}',
    'assignments.overdueOn': 'Overdue ({date})',
    'assignments.completedOn': 'Completed {date}',
    'assignments.completedLabel': 'Completed',
    'assignments.minutes': '{n} min',
    'assignments.accessRequestsTitle': 'Course access requests',
    'assignments.accessRequestsHint': 'Organization courses open after admin approval and payment confirmation.',
    'assignments.status.notStarted': 'Not started',
    'assignments.status.inProgress': 'In progress',
    'assignments.status.completed': 'Completed',
    'rewards.title': 'Rewards & Achievements',
    'rewards.subtitle': 'Earn points and badges by completing courses and passing exams.',
    'rewards.totalPoints': 'Total Points',
    'rewards.level': 'Level',
    'rewards.badgesEarned': 'Badges Earned',
    'rewards.coursesRewarded': 'Courses Rewarded',
    'rewards.progressTo': 'Progress to {level}',
    'rewards.pointsToNext': '{points} pts to go',
    'rewards.maxLevel': 'Top level reached — legendary! 🏆',
    'rewards.badges': 'Badges',
    'rewards.badgeLocked': 'Locked',
    'rewards.history': 'Reward History',
    'rewards.searchPlaceholder': 'Search rewards…',
    'rewards.filterAll': 'All types',
    'rewards.typeCertificate': 'Certificate',
    'rewards.typeBadge': 'Badge',
    'rewards.typePoints': 'Points',
    'rewards.typeHours': 'Hours',
    'rewards.from': 'From',
    'rewards.to': 'To',
    'rewards.reset': 'Reset',
    'rewards.empty': 'No rewards yet — complete a course to earn your first points!',
    'rewards.colDate': 'Date',
    'rewards.colType': 'Type',
    'rewards.colTitle': 'Reward',
    'rewards.colCourse': 'Course',
    'rewards.colValue': 'Value',
    'rewards.colRank': 'Rank',
    'rewards.leaderboard': 'Leaderboard',
    'rewards.you': 'you',
    'rewards.showing': 'Showing {shown} of {total}',
    'rewards.levelBronze': 'Bronze',
    'rewards.levelSilver': 'Silver',
    'rewards.levelGold': 'Gold',
    'rewards.levelPlatinum': 'Platinum',
    'rewards.levelLegend': 'Legend',
    'badge.first_course': 'First Course',
    'badge.first_course.desc': 'Completed your first course',
    'badge.five_courses': 'Dedicated Learner',
    'badge.five_courses.desc': 'Completed 5 courses',
    'badge.ten_courses': 'Knowledge Seeker',
    'badge.ten_courses.desc': 'Completed 10 courses',
    'badge.twenty_five_courses': 'Master Learner',
    'badge.twenty_five_courses.desc': 'Completed 25 courses',
    'badge.exam_passed': 'Exam Ace',
    'badge.exam_passed.desc': 'Passed an official exam',
    'badge.perfect_score': 'Perfect Score',
    'badge.perfect_score.desc': 'Scored 100% on an exam',
    'shell.library': 'Library',
    'shell.transcripts': 'Transcripts',
    'shell.rewards': 'Rewards',
    'player.backToCourse': 'Back to course',
    'player.lessons': 'Lessons',
    'player.closeLessons': 'Close lessons list',
    'player.courseFallback': 'Course',
    'player.courseMap': 'Course map',
    'player.learnerView': 'Learner view',
    'player.completePct': '{pct}% complete',
    'player.completedLessons': '{done}/{total} lessons',
    'player.completed': 'Completed',
    'player.inProgress': 'In progress',
    'player.noLessonsConfigured': 'No lessons/sections configured.',
    'player.lessonCounter': 'Lesson {current} / {total}',
    'player.interactionsCompleted': '{done}/{total} interactions completed',
    'player.noTrackedInteractions': 'No tracked interactions',
    'player.openSection': 'Open section',
    'player.audioLesson': 'Audio lesson',
    'player.reviewed': '{done} / {total} reviewed',
    'player.slideCounter': 'Slide {current} / {total}',
    'player.exploreTopics': 'Explore topics',
    'player.discovered': '{done} / {total} discovered',
    'player.transcript': 'Transcript',
    'player.noSlideContent': 'This slide has no narration or notes yet.',
    'player.previousSlide': 'Previous slide',
    'player.nextSlide': 'Next slide',
    'player.showSlide': 'Show slide {number}',
    'player.noSlides': 'No slides configured for this lesson block.',
    'player.noSlideImage': 'No slide image',
    'player.submit': 'Submit',
    'player.passed': 'Passed',
    'player.tryAgain': 'Try again',
    'player.quizHint': 'Select your answer then submit.',
    'player.previous': 'Previous',
    'player.saving': 'Saving...',
    'player.finishLesson': 'Finish lesson',
    'player.continue': 'Continue',
    'player.endCourse': 'End course',
    'player.noLessonSelected': 'No lesson selected',
    'player.selectLesson': 'Please select a lesson from the lessons list.',
    'player.loadingVideo': 'Loading video...',
    'player.gatedCard': 'Gated card',
    'player.flipCard': 'Flip card',
    'player.openPreviousCards': 'Open previous cards first',
    'player.discoverPreviousStep': 'Discover the previous step before revealing this one.',
    'player.openPreviousCardNotice': 'Open the previous card before continuing.',
    'player.reviewAllSlides': 'Review all {total} slides before continuing.',
    'player.discoverAllCards': 'Discover all {total} interactive cards before continuing.',
    'player.passQuiz': 'Pass the quiz before continuing.',
    'player.interactAll': 'Interact with all {total} required elements before continuing.',
    'player.completeInteractive': 'Complete the interactive slide content before continuing.',
    'player.finishInteractions': 'Finish the required interactions before continuing.',
    'player.noLessonsAvailable': 'No lessons available.',
    'player.movedToLesson': 'Moved to lesson {current} / {total}.',
    'player.lastLesson': 'You reached the last lesson.',
    'player.signInFirst': 'Please sign in first.',
    'player.lessonSaved': 'Lesson saved as completed.',
    'player.lessonSaveFailed': 'Failed to complete lesson.',
    'player.incompleteQuiz': 'This quiz is incomplete and has been skipped. Please notify your training administrator.',
    'player.slideDeckCardsNotice': 'All slides have been reviewed. Now open every interactive card to finish this lesson.',
    'player.slideDeckDoneNotice': 'All slides in this lesson have been reviewed. You can now mark it complete.',
    'player.passingScore': 'Passing score: {pct}%',
    'player.startQuiz': 'Start quiz',
    'player.continueButton': 'Continue',
    'player.sectionFallback': 'Section {number}',
    'player.explore': 'Explore',
    'player.hotspot': 'Hotspot',
    'player.stepReveal': 'Step reveal',
    'player.sequenceHint': 'Reveal the previous step first',
    'player.browserNoVideo': 'Your browser does not support the video tag.',
    'dashboard.title': 'Dashboard',
    'dashboard.kpiCards': 'Key Performance Indicators',
    'dashboard.activeCoursesLabel': 'Active Courses',
    'dashboard.completionRateLabel': 'Completion Rate',
    'dashboard.certificatesLabel': 'Certificates Earned',
    'dashboard.pointsLabel': 'Total Points',
    'dashboard.recentActivityLabel': 'Recent Activity',
    'dashboard.myProfileLabel': 'My Profile',
    'dashboard.viewProfileBtn': 'View Profile',
    'dashboard.myLevelLabel': 'Level',
    'dashboard.nextMilestoneLabel': 'Next Milestone',
    'dashboard.pointsToNextLabel': 'Points to Next Level',
    'dashboard.gamificationLabel': 'Gamification',
    'dashboard.recentCoursesLabel': 'Recent Courses',
    'dashboard.startNowBtn': 'Start Now',
    'dashboard.continueBtn': 'Continue',
    'dashboard.viewAllBtn': 'View All',
    'profile.title': 'Profile',
    'profile.subtitle': 'Manage your personal information and professional licenses.',
    'profile.editProfile': 'Edit Profile',
    'profile.personalInfo': 'Personal Information',
    'profile.contactInfo': 'Contact Information',
    'profile.organizationInfo': 'Organization Information',
    'profile.save': 'Save Changes',
    'profile.cancel': 'Cancel',
    'profile.tabProfile': 'Profile',
    'profile.tabLicenses': 'Licenses',
    'profile.fieldDisplayName': 'Display Name',
    'profile.fieldEmail': 'Email',
    'profile.fieldPhone': 'Phone',
    'profile.fieldAddress': 'Address',
    'profile.fieldProfileImage': 'Profile Image URL',
    'profile.urlPlaceholder': 'https://example.com/photo.jpg',
    'profile.fieldRole': 'Role',
    'profile.fieldTitle': 'Title',
    'profile.fieldDepartment': 'Department',
    'profile.fieldStatus': 'Status',
    'profile.myLicenses': 'My Licenses',
    'profile.addLicense': 'Add License',
    'profile.colState': 'State',
    'profile.colType': 'Type',
    'profile.colNumber': 'Number',
    'profile.colRenewal': 'Renewal Date',
    'profile.colRenewalPeriod': 'Renewal Period',
    'profile.colHours': 'Hours',
    'profile.colReminder': 'Reminder',
    'profile.months': 'months',
    'profile.weeks': 'weeks',
    'profile.noLicenses': 'No licenses added yet.',
    'profile.addEdit': 'Add / Edit License',
    'profile.saveLicense': 'Save License',
    'library.title': 'Library',
    'library.searchPlaceholder': 'Search courses',
    'library.loadMore': 'Load more',
    'library.noResults': 'No courses found',
    'library.filterAll': 'All',
    'library.noDescription': 'No description available.',
    'library.startOverview': 'View course',
    'transcript.title': 'Transcript',
    'transcript.courseTitle': 'Course',
    'transcript.status': 'Status',
    'transcript.grade': 'Grade',
    'transcript.completionDate': 'Completion Date',
    'transcript.score': 'Score',
    'transcript.downloadTranscript': 'Download Transcript',
    'transcript.filters': 'Filters',
    'transcript.searching': 'Searching...',
    'transcript.resetFilters': 'Reset Filters',
    'transcript.showing': 'Showing {shown} of {total}',
    'transcript.columns': 'Columns',
    'transcript.dueDate': 'Due Date',
    'transcript.completedDate': 'Completed Date',
    'transcript.dateRangeTip': 'Filter by completion date range.',
    'transcript.dueDateHint': 'Filter by due date range.',
    'transcript.searchPlaceholder': 'Search transcript…',
    'transcript.selectColumns': 'Select columns to display',
    'transcript.colTitle': 'Title',
    'transcript.colHours': 'Hours',
    'transcript.colGrade': 'Grade',
    'transcript.colCompleted': 'Completed',
    'transcript.colDue': 'Due',
    'transcript.colAction': 'Action',
    'transcript.colCertificate': 'Certificate',
    'transcript.courseId': 'Course ID',
    'transcript.getCertificate': 'Get Certificate',
    'transcript.noResults': 'No transcript entries found.',
    'policies.title': 'Policies and Procedures',
    'policies.acknowledge': 'Acknowledge',
    'policies.acknowledged': 'Acknowledged',
    'policies.pending': 'Pending',
    'policies.required': 'Required',
    'policies.dueDate': 'Due Date',
    'policies.searchPolicies': 'Search Policies and Procedures',
    'policies.searchPlaceholder': 'Search by title, area, owner…',
    'policies.readPolicies': 'Read policies and procedures',
    'policies.signInRequired': 'Please sign in to view policies.',
    'policies.titlesOnly': 'Titles only',
    'policies.titlesAndContent': 'Titles and content',
    'policies.allAreas': 'All areas',
    'policies.allOwners': 'All owners',
    'policies.allReferences': 'All references',
    'policies.results': '{count} results',
    'policies.noPoliciesFound': 'No policies found.',
    'policies.colTitle': 'Title',
    'policies.colPreview': 'Preview',
    'policies.colArea': 'Area',
    'policies.colLastRevised': 'Last Revised',
    'policies.colEffective': 'Effective',
    'policies.colLastApproved': 'Last Approved',
    'policies.badgeAck': 'Acknowledgement required',
    'policies.badgeBlocking': 'Blocking',
    'policies.badgeDone': 'Acknowledged',
    'policies.policyNotFound': 'Policy not found.',
    'policies.policyOwner': 'Owner',
    'policies.effective': 'Effective',
    'policies.chipAckRequired': 'Acknowledgement required',
    'policies.chipBlocking': 'Blocking',
    'policies.chipAcknowledged': 'Acknowledged',
    'policies.chipNotAcknowledged': 'Not acknowledged',
    'policies.btnAcknowledge': 'Acknowledge',
    'policies.btnAcknowledged': 'Acknowledged',
    'policies.signInToAcknowledge': 'Sign in to acknowledge this policy.',
    'policies.metaCategory': 'Category',
    'policies.metaArea': 'Area',
    'policies.metaOwner': 'Owner',
    'policies.metaLanguage': 'Language',
    'policies.metaLastRevised': 'Last Revised',
    'policies.metaNextReview': 'Next Review',
    'policies.tableOfContents': 'Table of Contents',
    'policies.policy': 'Policy',
    'policies.references': 'References',
    'certifications.title': 'Certifications',
    'certifications.official': 'Official Certifications',
    'certifications.completed': 'Completed',
    'certifications.inProgress': 'In Progress',
    'certifications.viewCertificate': 'View Certificate',
    'certifications.downloadCertificate': 'Download Certificate',
    'certifications.subtitle': 'View and share your earned certificates.',
    'certifications.downloadPdf': 'Download PDF',
    'certifications.sendEmail': 'Email Certificate',
    'certifications.certificateTitle': 'Certificate of Completion',
    'certifications.presentedTo': 'This certificate is presented to',
    'certifications.forCompleting': 'for successfully completing',
    'certifications.honor': 'Honor',
    'certifications.score': 'Score',
    'certifications.certificateNo': 'Certificate No.',
    'certifications.issued': 'Issued on',
    'certifications.signatory': 'Program Director',
    'certifications.signatoryRole': 'Innovacare Training',
    'certifications.notAvailable': 'Certificate Not Available',
    'certifications.notAvailableMessage': 'This certificate is not available yet. Complete the course to unlock it.',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.close': 'Close',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.view': 'View',
    'common.download': 'Download',
    'common.upload': 'Upload',
    'common.print': 'Print',
    'common.submit': 'Submit',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.save': 'Save',
    'common.clear': 'Clear',
    'common.share': 'Share',
    'common.from': 'From',
    'common.to': 'To',
    'common.loadMore': 'Load more',
    'common.backToAssignments': 'Back to Assignments',
  },
  fr: {
    'language.english': 'EN',
    'language.french': 'FR',
    'public.nav.home': 'Accueil',
    'public.nav.solutions': 'Solutions',
    'public.nav.industries': 'Industries',
    'public.nav.catalogue': 'Catalogue',
    'public.nav.pricing': 'Tarifs',
    'public.nav.ordre': 'Ordre Professionnel',
    'public.nav.verify': 'Vérifier un membre',
    'public.nav.faq': 'FAQ',
    'public.nav.login': 'Se connecter',
    'public.nav.demo': 'Réserver une démo',
    'public.nav.language': 'Langue',
    'shell.menuToggle': 'Ouvrir le menu',
    'shell.roleLearner': 'Apprenant',
    'shell.profile': 'Profil',
    'shell.logout': 'Deconnexion',
    'shell.primaryNav': 'Navigation principale',
    'shell.overview': 'Vue generale',
    'shell.resources': 'Ressources',
    'shell.dashboard': 'Tableau de bord',
    'shell.assignments': 'Formations assignees',
    'shell.woundLibrary': 'Zone de pratique rapide',
    'shell.profileLink': 'Votre profil',
    'shell.policies': 'Politiques et procedures',
    'shell.certifications': 'Certifications',
    'shell.officialCertifications': 'Certifications officielles',
    'shell.onsiteExams': 'Examens sur site',
    'shell.verifyMember': 'Vérifier un membre',
    'assignments.title': 'Mes formations assignées',
    'assignments.subtitle': 'Vos formations assignées, triées par priorité.',
    'assignments.searchPlaceholder': 'Rechercher un cours…',
    'assignments.sortBy': 'Trier par',
    'assignments.sortDue': "Date d'échéance",
    'assignments.sortAz': 'Titre (A–Z)',
    'assignments.sortKind': 'Type',
    'assignments.tabActive': 'En cours',
    'assignments.tabCompleted': 'Terminées',
    'assignments.statActive': 'En cours',
    'assignments.statOverdue': 'En retard',
    'assignments.statCompleted': 'Terminées',
    'assignments.emptyActive': 'Aucune formation en cours — vous êtes à jour ! 🎉',
    'assignments.emptyCompleted': 'Aucun cours terminé pour le moment.',
    'assignments.start': 'Commencer',
    'assignments.resume': 'Reprendre',
    'assignments.review': 'Revoir',
    'assignments.addToCalendar': 'Ajouter au calendrier',
    'assignments.googleCalendar': 'Google Agenda',
    'assignments.downloadIcs': 'Télécharger .ics (Outlook/Apple)',
    'assignments.noDueDate': "Pas de date d'échéance",
    'assignments.overdue': 'En retard',
    'assignments.dueOn': 'Échéance {date}',
    'assignments.overdueOn': 'En retard ({date})',
    'assignments.completedOn': 'Terminé le {date}',
    'assignments.completedLabel': 'Terminé',
    'assignments.minutes': '{n} min',
    'assignments.accessRequestsTitle': "Demandes d'accès aux cours",
    'assignments.accessRequestsHint': "Les cours de l'organisation s'ouvrent après approbation de l'administrateur et confirmation du paiement.",
    'assignments.status.notStarted': 'Non commencé',
    'assignments.status.inProgress': 'En cours',
    'assignments.status.completed': 'Terminé',
    'rewards.title': 'Récompenses et réussites',
    'rewards.subtitle': 'Gagnez des points et des badges en terminant des cours et en réussissant des examens.',
    'rewards.totalPoints': 'Points totaux',
    'rewards.level': 'Niveau',
    'rewards.badgesEarned': 'Badges obtenus',
    'rewards.coursesRewarded': 'Cours récompensés',
    'rewards.progressTo': 'Progression vers {level}',
    'rewards.pointsToNext': 'encore {points} pts',
    'rewards.maxLevel': 'Niveau maximum atteint — légendaire ! 🏆',
    'rewards.badges': 'Badges',
    'rewards.badgeLocked': 'Verrouillé',
    'rewards.history': 'Historique des récompenses',
    'rewards.searchPlaceholder': 'Rechercher une récompense…',
    'rewards.filterAll': 'Tous les types',
    'rewards.typeCertificate': 'Certificat',
    'rewards.typeBadge': 'Badge',
    'rewards.typePoints': 'Points',
    'rewards.typeHours': 'Heures',
    'rewards.from': 'Du',
    'rewards.to': 'Au',
    'rewards.reset': 'Réinitialiser',
    'rewards.empty': 'Aucune récompense pour le moment — terminez un cours pour gagner vos premiers points !',
    'rewards.colDate': 'Date',
    'rewards.colType': 'Type',
    'rewards.colTitle': 'Récompense',
    'rewards.colCourse': 'Cours',
    'rewards.colValue': 'Valeur',
    'rewards.colRank': 'Rang',
    'rewards.leaderboard': 'Classement',
    'rewards.you': 'vous',
    'rewards.showing': '{shown} sur {total} affichés',
    'rewards.levelBronze': 'Bronze',
    'rewards.levelSilver': 'Argent',
    'rewards.levelGold': 'Or',
    'rewards.levelPlatinum': 'Platine',
    'rewards.levelLegend': 'Légende',
    'badge.first_course': 'Premier cours',
    'badge.first_course.desc': 'Vous avez terminé votre premier cours',
    'badge.five_courses': 'Apprenant assidu',
    'badge.five_courses.desc': '5 cours terminés',
    'badge.ten_courses': 'Chercheur de savoir',
    'badge.ten_courses.desc': '10 cours terminés',
    'badge.twenty_five_courses': 'Maître apprenant',
    'badge.twenty_five_courses.desc': '25 cours terminés',
    'badge.exam_passed': "As de l'examen",
    'badge.exam_passed.desc': 'Examen officiel réussi',
    'badge.perfect_score': 'Score parfait',
    'badge.perfect_score.desc': '100 % à un examen',
    'Dashboard': 'Tableau de bord',
    'Assignment Center': "Centre d'assignation",
    'Access Requests': "Demandes d'accès",
    'Learner Directory': 'Répertoire des apprenants',
    'Course Library': 'Bibliothèque de cours',
    'Kiosk Exam Sessions': "Sessions d'examen kiosque",
    'Onsite Exam Center': "Centre d'examens sur site",
    'Official Certifications': 'Certifications officielles',
    'Exam Blueprint Center': "Centre de plans d'examen",
    'Member Registry': 'Registre des membres',
    'Verify Membership': 'Vérifier un membre',
    'Notifications': 'Notifications',
    'Notification Center': 'Centre de notifications',
    'Policies': 'Politiques',
    'Policy Library': 'Bibliothèque de politiques',
    'Policy Assignments': 'Assignations de politiques',
    'Policy Reports': 'Rapports de politiques',
    'Compliance Matrix': 'Matrice de conformité',
    'Audit Center': "Centre d'audit",
    'Clinical Resources': 'Ressources cliniques',
    'Settings': 'Paramètres',
    'Reports': 'Rapports',
    'Operations': 'Opérations',
    'Compliance': 'Conformité',
    'Communications': 'Communications',
    'Organization': 'Organisation',
    'Command Center': 'Centre de commande',
    'Audit & Acknowledgements': 'Audit et attestations',
    'Policy Assignment': 'Assignation de politiques',
    'Governance Settings': 'Paramètres de gouvernance',
    'Quick Practice Zone': 'Zone de pratique rapide',
    'Public Organization Page': "Page publique de l'organisation",
    'KPIs, readiness and alerts': 'Indicateurs, préparation et alertes',
    'Bulk assign and due dates': 'Assignation en masse et échéances',
    'Approve individual access and payment': "Approuver l'accès individuel et le paiement",
    'Track learner activity': "Suivre l'activité des apprenants",
    'Review approved courses': 'Consulter les cours approuvés',
    'Manage exam centers and secure kiosk sessions': "Gérer les centres d'examen et les sessions kiosque sécurisées",
    'Results, publication and card delivery for kiosk exams': 'Résultats, publication et remise des cartes pour les examens kiosque',
    'Certification sessions and candidate orchestration': 'Sessions de certification et gestion des candidats',
    'Create and manage exam blueprints for sessions': "Créer et gérer les plans d'examen des sessions",
    'Verify members registered on the roster': 'Vérifier les membres inscrits au registre',
    'Look up a single member by number': 'Rechercher un membre par numéro',
    'Evidence, attestations, policy status': 'Preuves, attestations, statut des politiques',
    'Learners vs required courses': 'Apprenants vs cours requis',
    'Create, edit and review policy governance': 'Créer, modifier et réviser la gouvernance des politiques',
    'Assign tenant policies to learners': 'Assigner les politiques aux apprenants',
    'Program and notification rules': 'Règles du programme et des notifications',
    'Broadcast reminders and updates': 'Diffuser rappels et mises à jour',
    'Org quick sheets and task refreshers': 'Fiches rapides et rappels de tâches',
    'View your organization public page': "Voir la page publique de votre organisation",
    'Sign out': 'Se déconnecter',
    'Manager': 'Gestionnaire',
    'Training Portal': 'Portail de formation',
    'shell.library': 'Bibliotheque',
    'shell.transcripts': 'Releves',
    'shell.rewards': 'Recompenses',
    'player.backToCourse': 'Retour au cours',
    'player.lessons': 'Lecons',
    'player.closeLessons': 'Fermer la liste des lecons',
    'player.courseFallback': 'Cours',
    'player.courseMap': 'Plan du cours',
    'player.learnerView': 'Vue apprenant',
    'player.completePct': '{pct}% termine',
    'player.completedLessons': '{done}/{total} lecons',
    'player.completed': 'Termine',
    'player.inProgress': 'En cours',
    'player.noLessonsConfigured': 'Aucune lecon/section configuree.',
    'player.lessonCounter': 'Lecon {current} / {total}',
    'player.interactionsCompleted': '{done}/{total} interactions terminees',
    'player.noTrackedInteractions': 'Aucune interaction suivie',
    'player.openSection': 'Ouvrir la section',
    'player.audioLesson': 'Lecon audio',
    'player.reviewed': '{done} / {total} consultees',
    'player.slideCounter': 'Slide {current} / {total}',
    'player.exploreTopics': 'Explorer les sujets',
    'player.discovered': '{done} / {total} decouverts',
    'player.transcript': 'Transcription',
    'player.noSlideContent': 'Cette slide n’a pas encore de narration ou de notes.',
    'player.previousSlide': 'Slide precedente',
    'player.nextSlide': 'Slide suivante',
    'player.showSlide': 'Afficher la slide {number}',
    'player.noSlides': 'Aucune slide configuree pour ce bloc de lecon.',
    'player.noSlideImage': 'Aucune image de slide',
    'player.submit': 'Soumettre',
    'player.passed': 'Reussi',
    'player.tryAgain': 'Reessayer',
    'player.quizHint': 'Selectionnez votre reponse puis soumettez.',
    'player.previous': 'Precedent',
    'player.saving': 'Enregistrement...',
    'player.finishLesson': 'Terminer la lecon',
    'player.continue': 'Continuer',
    'player.endCourse': 'Finir le cours',
    'player.noLessonSelected': 'Aucune lecon selectionnee',
    'player.selectLesson': 'Selectionnez une lecon dans la liste.',
    'player.loadingVideo': 'Chargement de la video...',
    'player.gatedCard': 'Carte verrouillee',
    'player.flipCard': 'Carte a retourner',
    'player.openPreviousCards': 'Ouvrez d’abord les cartes precedentes',
    'player.discoverPreviousStep': 'Decouvrez l’etape precedente avant d’ouvrir celle-ci.',
    'player.openPreviousCardNotice': 'Ouvrez la carte precedente avant de continuer.',
    'player.reviewAllSlides': 'Consultez les {total} slides avant de continuer.',
    'player.discoverAllCards': 'Decouvrez les {total} cartes interactives avant de continuer.',
    'player.passQuiz': 'Reussissez le quiz avant de continuer.',
    'player.interactAll': 'Completez les {total} interactions requises avant de continuer.',
    'player.completeInteractive': 'Completez le contenu interactif avant de continuer.',
    'player.finishInteractions': 'Terminez les interactions requises avant de continuer.',
    'player.noLessonsAvailable': 'Aucune lecon disponible.',
    'player.movedToLesson': 'Lecon {current} / {total}.',
    'player.lastLesson': 'Vous avez atteint la derniere lecon.',
    'player.signInFirst': 'Veuillez vous connecter d’abord.',
    'player.lessonSaved': 'Lecon enregistree comme terminee.',
    'player.lessonSaveFailed': 'Impossible de terminer la lecon.',
    'player.incompleteQuiz': 'Ce quiz est incomplet et a ete ignore. Veuillez informer votre administrateur de formation.',
    'player.slideDeckCardsNotice': 'Toutes les slides ont ete consultees. Ouvrez maintenant toutes les cartes interactives pour terminer cette lecon.',
    'player.slideDeckDoneNotice': 'Toutes les slides de cette lecon ont ete consultees. Vous pouvez maintenant la marquer comme terminee.',
    'player.passingScore': 'Score de reussite : {pct}%',
    'player.startQuiz': 'Demarrer le quiz',
    'player.continueButton': 'Continuer',
    'player.sectionFallback': 'Section {number}',
    'player.explore': 'Explorer',
    'player.hotspot': 'Point interactif',
    'player.stepReveal': 'Etape',
    'player.sequenceHint': 'Revelez d’abord l’etape precedente',
    'player.browserNoVideo': 'Votre navigateur ne prend pas en charge la balise video.',
    'dashboard.title': 'Tableau de bord',
    'dashboard.kpiCards': 'Indicateurs clés de performance',
    'dashboard.activeCoursesLabel': 'Cours actifs',
    'dashboard.completionRateLabel': 'Taux de complétion',
    'dashboard.certificatesLabel': 'Certificats obtenu',
    'dashboard.pointsLabel': 'Points totaux',
    'dashboard.recentActivityLabel': 'Activité récente',
    'dashboard.myProfileLabel': 'Mon profil',
    'dashboard.viewProfileBtn': 'Voir le profil',
    'dashboard.myLevelLabel': 'Niveau',
    'dashboard.nextMilestoneLabel': 'Prochaine étape',
    'dashboard.pointsToNextLabel': 'Points pour le prochain niveau',
    'dashboard.gamificationLabel': 'Gamification',
    'dashboard.recentCoursesLabel': 'Cours récents',
    'dashboard.startNowBtn': 'Commencer maintenant',
    'dashboard.continueBtn': 'Continuer',
    'dashboard.viewAllBtn': 'Voir tout',
    'profile.title': 'Profil',
    'profile.subtitle': 'Gérez vos informations personnelles et vos licences professionnelles.',
    'profile.editProfile': 'Modifier le profil',
    'profile.personalInfo': 'Informations personnelles',
    'profile.contactInfo': 'Informations de contact',
    'profile.organizationInfo': 'Informations organisationnelles',
    'profile.save': 'Enregistrer les modifications',
    'profile.cancel': 'Annuler',
    'profile.tabProfile': 'Profil',
    'profile.tabLicenses': 'Licences',
    'profile.fieldDisplayName': 'Nom affiché',
    'profile.fieldEmail': 'Courriel',
    'profile.fieldPhone': 'Téléphone',
    'profile.fieldAddress': 'Adresse',
    'profile.fieldProfileImage': "URL de l'image de profil",
    'profile.urlPlaceholder': 'https://exemple.com/photo.jpg',
    'profile.fieldRole': 'Rôle',
    'profile.fieldTitle': 'Titre',
    'profile.fieldDepartment': 'Département',
    'profile.fieldStatus': 'Statut',
    'profile.myLicenses': 'Mes licences',
    'profile.addLicense': 'Ajouter une licence',
    'profile.colState': 'État/Province',
    'profile.colType': 'Type',
    'profile.colNumber': 'Numéro',
    'profile.colRenewal': 'Date de renouvellement',
    'profile.colRenewalPeriod': 'Période de renouvellement',
    'profile.colHours': 'Heures',
    'profile.colReminder': 'Rappel',
    'profile.months': 'mois',
    'profile.weeks': 'semaines',
    'profile.noLicenses': 'Aucune licence ajoutée pour le moment.',
    'profile.addEdit': 'Ajouter / Modifier une licence',
    'profile.saveLicense': 'Enregistrer la licence',
    'library.title': 'Bibliothèque',
    'library.searchPlaceholder': 'Rechercher des cours',
    'library.loadMore': 'Charger plus',
    'library.noResults': 'Aucun cours trouvé',
    'library.filterAll': 'Tous',
    'library.noDescription': 'Aucune description disponible.',
    'library.startOverview': 'Voir le cours',
    'transcript.title': 'Relevé de notes',
    'transcript.courseTitle': 'Cours',
    'transcript.status': 'Statut',
    'transcript.grade': 'Note',
    'transcript.completionDate': 'Date de complétion',
    'transcript.score': 'Score',
    'transcript.downloadTranscript': 'Télécharger le relevé',
    'transcript.filters': 'Filtres',
    'transcript.searching': 'Recherche...',
    'transcript.resetFilters': 'Réinitialiser les filtres',
    'transcript.showing': '{shown} sur {total} affichés',
    'transcript.columns': 'Colonnes',
    'transcript.dueDate': "Date d'échéance",
    'transcript.completedDate': 'Date de complétion',
    'transcript.dateRangeTip': 'Filtrer par plage de dates de complétion.',
    'transcript.dueDateHint': "Filtrer par plage de dates d'échéance.",
    'transcript.searchPlaceholder': 'Rechercher dans le relevé…',
    'transcript.selectColumns': 'Sélectionner les colonnes à afficher',
    'transcript.colTitle': 'Titre',
    'transcript.colHours': 'Heures',
    'transcript.colGrade': 'Note',
    'transcript.colCompleted': 'Complété',
    'transcript.colDue': 'Échéance',
    'transcript.colAction': 'Action',
    'transcript.colCertificate': 'Certificat',
    'transcript.courseId': 'ID du cours',
    'transcript.getCertificate': 'Obtenir le certificat',
    'transcript.noResults': 'Aucune entrée trouvée dans le relevé.',
    'policies.title': 'Politiques et procédures',
    'policies.acknowledge': 'Reconnaître',
    'policies.acknowledged': 'Reconnu',
    'policies.pending': 'En attente',
    'policies.required': 'Requis',
    'policies.dueDate': 'Date d\'échéance',
    'policies.searchPolicies': 'Rechercher dans les politiques et procédures',
    'policies.searchPlaceholder': 'Rechercher par titre, secteur, responsable…',
    'policies.readPolicies': 'Consulter les politiques et procédures',
    'policies.signInRequired': 'Veuillez vous connecter pour consulter les politiques.',
    'policies.titlesOnly': 'Titres seulement',
    'policies.titlesAndContent': 'Titres et contenu',
    'policies.allAreas': 'Tous les secteurs',
    'policies.allOwners': 'Tous les responsables',
    'policies.allReferences': 'Toutes les références',
    'policies.results': '{count} résultats',
    'policies.noPoliciesFound': 'Aucune politique trouvée.',
    'policies.colTitle': 'Titre',
    'policies.colPreview': 'Aperçu',
    'policies.colArea': 'Secteur',
    'policies.colLastRevised': 'Dernière révision',
    'policies.colEffective': 'Entrée en vigueur',
    'policies.colLastApproved': 'Dernière approbation',
    'policies.badgeAck': 'Confirmation requise',
    'policies.badgeBlocking': 'Bloquant',
    'policies.badgeDone': 'Confirmé',
    'policies.policyNotFound': 'Politique introuvable.',
    'policies.policyOwner': 'Responsable',
    'policies.effective': 'En vigueur',
    'policies.chipAckRequired': 'Confirmation requise',
    'policies.chipBlocking': 'Bloquant',
    'policies.chipAcknowledged': 'Confirmé',
    'policies.chipNotAcknowledged': 'Non confirmé',
    'policies.btnAcknowledge': 'Confirmer',
    'policies.btnAcknowledged': 'Confirmé',
    'policies.signInToAcknowledge': 'Connectez-vous pour confirmer cette politique.',
    'policies.metaCategory': 'Catégorie',
    'policies.metaArea': 'Secteur',
    'policies.metaOwner': 'Responsable',
    'policies.metaLanguage': 'Langue',
    'policies.metaLastRevised': 'Dernière révision',
    'policies.metaNextReview': 'Prochaine révision',
    'policies.tableOfContents': 'Table des matières',
    'policies.policy': 'Politique',
    'policies.references': 'Références',
    'certifications.title': 'Certifications',
    'certifications.official': 'Certifications officielles',
    'certifications.completed': 'Complétée',
    'certifications.inProgress': 'En cours',
    'certifications.viewCertificate': 'Voir le certificat',
    'certifications.downloadCertificate': 'Télécharger le certificat',
    'certifications.subtitle': 'Consultez et partagez vos certificats obtenus.',
    'certifications.downloadPdf': 'Télécharger le PDF',
    'certifications.sendEmail': 'Envoyer par courriel',
    'certifications.certificateTitle': "Certificat d'achèvement",
    'certifications.presentedTo': 'Ce certificat est décerné à',
    'certifications.forCompleting': 'pour avoir complété avec succès',
    'certifications.honor': 'Mention',
    'certifications.score': 'Score',
    'certifications.certificateNo': 'N° de certificat',
    'certifications.issued': 'Délivré le',
    'certifications.signatory': 'Directeur du programme',
    'certifications.signatoryRole': 'Innovacare Training',
    'certifications.notAvailable': 'Certificat non disponible',
    'certifications.notAvailableMessage': "Ce certificat n'est pas encore disponible. Complétez le cours pour le débloquer.",
    'common.search': 'Rechercher',
    'common.filter': 'Filtrer',
    'common.sort': 'Trier',
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.success': 'Succès',
    'common.back': 'Retour',
    'common.next': 'Suivant',
    'common.previous': 'Précédent',
    'common.close': 'Fermer',
    'common.delete': 'Supprimer',
    'common.edit': 'Modifier',
    'common.add': 'Ajouter',
    'common.view': 'Voir',
    'common.download': 'Télécharger',
    'common.upload': 'Téléverser',
    'common.print': 'Imprimer',
    'common.submit': 'Soumettre',
    'common.cancel': 'Annuler',
    'common.confirm': 'Confirmer',
    'common.yes': 'Oui',
    'common.no': 'Non',
    'common.save': 'Enregistrer',
    'common.clear': 'Effacer',
    'common.share': 'Partager',
    'common.from': 'De',
    'common.to': 'À',
    'common.loadMore': 'Charger plus',
    'common.backToAssignments': 'Retour aux formations assignées',
  },
};

const PUBLIC_TEXT_EN: Record<string, string> = {
  'Nouveaux marchés': 'New markets',
  'LMS pour équipes non médicales': 'LMS for non-medical teams',
  'Industries': 'Industries',
  'Vendre la plateforme au-delà de la santé': 'Sell the platform beyond healthcare',
  'LMS pour plusieurs industries': 'LMS for multiple industries',
  'Innovacare Training peut aussi former les équipes hors santé': 'Innovacare Training can also train teams outside healthcare',
  'La plateforme peut être vendue aux entreprises qui doivent organiser l’onboarding, la conformité, les procédures internes, les quiz, les certificats et le suivi des apprenants dans un espace clair.': 'The platform can be sold to companies that need to organize onboarding, compliance, internal procedures, quizzes, certificates and learner tracking in one clear workspace.',
  'Voir les plans': 'View plans',
  'Capacités principales': 'Core capabilities',
  'Plateforme multi-organisations': 'Multi-organization platform',
  'Assignation par rôle ou équipe': 'Assignment by role or team',
  'Suivi manager et relances': 'Manager tracking and reminders',
  'Quiz, attestations et certificats': 'Quizzes, attestations and certificates',
  'Pages publiques multilingues': 'Multilingual public pages',
  'Aperçu de plateforme de formation': 'Training platform preview',
  'Tableau de bord de formation': 'Training dashboard',
  'Assignation': 'Assignment',
  'Par rôle, site ou équipe': 'By role, site or team',
  'Preuves': 'Evidence',
  'Certificats et complétions': 'Certificates and completions',
  'Marchés cibles': 'Target markets',
  'Une plateforme de formation adaptable à plusieurs types d’entreprise': 'A training platform adaptable to many company types',
  'Le produit reste utile partout où une organisation doit former, vérifier, documenter et suivre la progression de ses équipes.': 'The product is useful anywhere an organization needs to train, verify, document and track team progress.',
  'Services professionnels': 'Professional services',
  'Onboarding, politiques internes, formation client et montée en compétence des équipes.': 'Onboarding, internal policies, client training and team upskilling.',
  'Industrie & fabrication': 'Industry and manufacturing',
  'SOP, sécurité, qualité, maintenance et formation des opérateurs sur plusieurs sites.': 'SOPs, safety, quality, maintenance and operator training across multiple sites.',
  'Construction & sécurité': 'Construction and safety',
  'Parcours sécurité, procédures terrain, attestations et suivi des formations obligatoires.': 'Safety pathways, field procedures, attestations and required training tracking.',
  'Commerce & franchises': 'Retail and franchises',
  'Formation produit, service client, standards de marque et intégration des nouveaux employés.': 'Product training, customer service, brand standards and new employee onboarding.',
  'Logistique & équipes terrain': 'Logistics and field teams',
  'Procédures opérationnelles, conformité, checklists et préparation des équipes mobiles.': 'Operational procedures, compliance, checklists and mobile team readiness.',
  'Éducation & associations': 'Education and associations',
  'Programmes de formation, ressources, quiz et certificats pour communautés et apprenants.': 'Training programs, resources, quizzes and certificates for communities and learners.',
  'Hôtellerie & services': 'Hospitality and services',
  'Standards de service, hygiène, accueil, procédures internes et suivi des compétences.': 'Service standards, hygiene, guest experience, internal procedures and skill tracking.',
  'Technologie & support': 'Technology and support',
  'Base de connaissances, formation produit, support client et certification interne.': 'Knowledge base, product training, customer support and internal certification.',
  'Cas d’usage': 'Use cases',
  'Le même moteur LMS, avec des contenus adaptés à chaque secteur': 'The same LMS engine, with content adapted to each sector',
  'Onboarding des nouveaux employés': 'New employee onboarding',
  'Créez des parcours cohérents pour accélérer l’intégration et réduire les oublis.': 'Create consistent pathways to speed up onboarding and reduce missed steps.',
  'Formation sécurité et conformité': 'Safety and compliance training',
  'Assignez les modules obligatoires, suivez les retards et conservez les preuves.': 'Assign required modules, track delays and keep evidence.',
  'Procédures internes et SOP': 'Internal procedures and SOPs',
  'Transformez vos procédures en contenus clairs avec quiz, ressources et validation.': 'Turn procedures into clear content with quizzes, resources and validation.',
  'Certificats et rapports': 'Certificates and reports',
  'Gardez un historique lisible des complétions, scores, certificats et validations.': 'Keep a readable history of completions, scores, certificates and validations.',
  'Positionnement commercial': 'Sales positioning',
  'Un message plus large sans perdre la spécialité santé': 'A broader message without losing the healthcare specialty',
  'La page santé peut rester ciblée pour les organisations médicales, pendant que cette page ouvre la porte aux compagnies qui veulent un LMS simple, traçable et rapide à déployer pour leurs propres procédures.': 'The healthcare page can stay focused on medical organizations, while this page opens the door to companies that want a simple, traceable LMS they can deploy quickly for their own procedures.',
  'À vendre comme': 'Sell it as',
  'Parler d’un déploiement': 'Discuss a rollout',
  'Plateforme LMS pour organisations modernes': 'LMS platform for modern organizations',
  'Parcours santé': 'Healthcare pathways',
  'Onboarding, conformité et pilotage': 'Onboarding, compliance and oversight',
  'Plateforme LMS santé': 'Healthcare LMS platform',
  'Accédez aux pages publiques sans liens cassés': 'Browse public pages without broken links',
  'Plateforme de formation en santé • LMS santé': 'Healthcare training platform • Healthcare LMS',
  'Formez vos équipes de santé avec plus de rigueur, de visibilité et de simplicité': 'Train healthcare teams with more rigor, visibility and simplicity',
  'Innovacare Training aide les organisations de santé à centraliser les parcours d’onboarding, les formations de conformité, les modules cliniques, les quiz et le suivi des apprenants dans une seule plateforme moderne.': 'Innovacare Training helps healthcare organizations centralize onboarding pathways, compliance training, clinical modules, quizzes and learner tracking in one modern platform.',
  'Demander une démo': 'Request a demo',
  'Voir les catégories': 'View categories',
  'Onboarding structuré': 'Structured onboarding',
  'Conformité et traçabilité': 'Compliance and traceability',
  'Suivi de progression': 'Progress tracking',
  'Certificats et évaluations': 'Certificates and assessments',
  'Conçu pour les organisations de santé': 'Built for healthcare organizations',
  'Pensé pour la formation des équipes': 'Designed for team training',
  'Suivi clair des complétions': 'Clear completion tracking',
  'Parcours plus structurés et documentés': 'More structured, documented pathways',
  'Formation dispersée entre documents, PDF, messages et supports multiples': 'Training scattered across documents, PDFs, messages and multiple resources',
  'Onboarding du personnel non standardisé selon les services ou sites': 'Staff onboarding that is not standardized across departments or sites',
  'Suivi manuel chronophage pour les managers et responsables de formation': 'Manual tracking that consumes time for managers and training leads',
  'Manque de visibilité sur les formations réellement complétées': 'Limited visibility into training that was actually completed',
  'Difficulté à documenter les résultats, validations et certificats': 'Difficulty documenting results, validations and certificates',
  'Manque d’homogénéité entre équipes, services ou structures': 'Inconsistent practices across teams, departments or organizations',
  'Assignation des cours par rôle, équipe ou organisation': 'Course assignment by role, team or organization',
  'Suivi centralisé des apprenants avec vue consolidée': 'Centralized learner tracking with a consolidated view',
  'Évaluations et quiz intégrés pour vérifier les acquis': 'Built-in assessments and quizzes to validate learning',
  'Certificats et historiques de complétion facilement accessibles': 'Easy access to certificates and completion history',
  'Bibliothèque documentaire structurée pour les contenus pédagogiques': 'Structured document library for learning content',
  'Gestion multi-organisations avec meilleure visibilité manager': 'Multi-organization management with better manager visibility',
  'Assignation des cours': 'Course assignment',
  'Attribuez les formations selon les rôles, équipes ou structures.': 'Assign training by role, team or organization.',
  'Progression des apprenants': 'Learner progress',
  'Suivez l’avancement, les complétions et les retards.': 'Track progress, completions and delays.',
  'Quiz & évaluations': 'Quizzes and assessments',
  'Vérifiez les acquis avec des évaluations structurées.': 'Validate learning with structured assessments.',
  'Certificats': 'Certificates',
  'Documentez les résultats et les validations.': 'Document results and validations.',
  'Gestion des rôles': 'Role management',
  'Expériences distinctes pour admins, managers et apprenants.': 'Distinct experiences for admins, managers and learners.',
  'Bibliothèque de ressources': 'Resource library',
  'Centralisez politiques, procédures et supports pédagogiques.': 'Centralize policies, procedures and learning resources.',
  'Standardisez l’intégration du personnel et les parcours clés.': 'Standardize staff onboarding and key pathways.',
  'Vue manager / admin': 'Manager / admin view',
  'Donnez une vision claire de l’activité de formation.': 'Give leaders a clear view of training activity.',
  'Parcours pour coordination à domicile et équipes terrain.': 'Pathways for home coordination and field teams.',
  'Modules conçus pour les besoins de soins à domicile.': 'Modules designed for home health needs.',
  'Pour SNF, préparation clinique et standardisation.': 'For SNF, clinical preparation and standardization.',
  'Parcours adaptés à l’accompagnement et à la coordination.': 'Pathways adapted to support and coordination.',
  'Organisation plus fluide des parcours hospitaliers.': 'More fluid organization of hospital pathways.',
  'Pour cabinets, cliniques et petites structures.': 'For practices, clinics and small organizations.',
  'Formation conformité, procédures et traçabilité.': 'Compliance training, procedures and traceability.',
  'Préparez les équipes avec des parcours concrets.': 'Prepare teams with practical pathways.',
  'Organiser les contenus': 'Organize content',
  'Regroupez modules, procédures, ressources et évaluations.': 'Group modules, procedures, resources and assessments.',
  'Assigner les parcours': 'Assign pathways',
  'Diffusez les formations selon les rôles ou structures.': 'Distribute training by role or organization.',
  'Suivre les progrès': 'Track progress',
  'Visualisez l’avancement et les complétions.': 'View progress and completions.',
  'Documenter les résultats': 'Document results',
  'Conservez un historique clair des validations et certificats.': 'Keep a clear history of validations and certificates.',
  'Standardiser l’onboarding': 'Standardize onboarding',
  'Structurer les parcours de formation': 'Structure training pathways',
  'Améliorer la visibilité managériale': 'Improve manager visibility',
  'Réduire le suivi manuel': 'Reduce manual tracking',
  'Renforcer la traçabilité': 'Strengthen traceability',
  'Soutenir la préparation organisationnelle': 'Support organizational readiness',
  'Accéder facilement aux formations assignées': 'Easily access assigned training',
  'Suivre une progression claire': 'Follow clear progress',
  'Compléter les modules plus simplement': 'Complete modules more easily',
  'Réussir les évaluations': 'Pass assessments',
  'Retrouver certificats et contenus dans un espace unique': 'Find certificates and content in one place',
  'Visibilité': 'Visibility',
  'Responsabilité': 'Accountability',
  'Traçabilité': 'Traceability',
  'Standardisation': 'Standardization',
  'Préparation des équipes': 'Team readiness',
  'Meilleure gouvernance': 'Better governance',
  'À qui s’adresse Innovacare Training ?': 'Who is Innovacare Training for?',
  'Innovacare Training s’adresse aux organisations de santé, responsables de formation, administrateurs, managers et professionnels qui souhaitent mieux structurer la formation du personnel, l’onboarding et le suivi des parcours.': 'Innovacare Training is for healthcare organizations, training leads, administrators, managers and professionals who want to better structure staff training, onboarding and pathway tracking.',
  'Peut-on assigner des cours selon les rôles ou équipes ?': 'Can courses be assigned by role or team?',
  'Oui. Les contenus peuvent être assignés selon les rôles, équipes, services ou structures, pour une gestion de la formation plus cohérente et plus adaptée au terrain.': 'Yes. Content can be assigned by role, team, department or organization for training management that is more consistent and adapted to the field.',
  'Les apprenants peuvent-ils suivre leur progression ?': 'Can learners track their progress?',
  'Oui. Les apprenants disposent d’une vue claire sur leurs modules assignés, leur progression, leurs évaluations et leurs validations dans un espace unique.': 'Yes. Learners get a clear view of assigned modules, progress, assessments and validations in one place.',
  'La plateforme permet-elle de gérer les certificats ?': 'Can the platform manage certificates?',
  'Oui. Innovacare Training aide à documenter les complétions et à conserver un historique clair des certificats, validations et résultats associés à chaque parcours.': 'Yes. Innovacare Training helps document completions and keep a clear history of certificates, validations and results tied to each pathway.',
  'Innovacare Training peut-il être utilisé pour plusieurs structures ou organisations ?': 'Can Innovacare Training support multiple organizations?',
  'Oui. Le produit est pensé pour une gestion multi-organisations permettant de piloter plusieurs structures tout en gardant une logique de standardisation et de visibilité centralisée.': 'Yes. The product is designed for multi-organization management so leaders can oversee several structures while keeping standardization and centralized visibility.',
  'Parcours actifs': 'Active pathways',
  'Taux de complétion': 'Completion rate',
  'Certificats validés': 'Certificates validated',
  'Onboarding du personnel': 'Staff onboarding',
  'Formation conformité': 'Compliance training',
  'Prévention clinique': 'Clinical prevention',
  'Parcours par rôle': 'Role-based pathways',
  'Assignez par équipe, manager ou organisation.': 'Assign by team, manager or organization.',
  'Quiz intégrés': 'Built-in quizzes',
  'Évaluez les acquis avec plus de cohérence.': 'Assess learning more consistently.',
  'Documentez les validations et les complétions.': 'Document validations and completions.',
  'Multi-organisations': 'Multi-organization',
  'Pilotez plusieurs structures depuis une base claire.': 'Manage multiple structures from one clear base.',
  'Fonctionnalités': 'Features',
  'Explorez les modules clés de la plateforme': 'Explore the platform’s key modules',
  'Tarifs': 'Pricing',
  'Comparez les plans et réservez une démo': 'Compare plans and book a demo',
  'Catalogue santé': 'Healthcare catalogue',
  'Catalogue de cours': 'Course catalogue',
  'Explorez une bibliothèque de formation professionnelle pensée pour la santé': 'Explore a professional training library built for healthcare',
  'Accédez à un catalogue complet et filtrez les cours par type, domaine, langue, audience et contexte de soins pour trouver la formation idéale.': 'Access a complete catalogue and filter courses by type, domain, language, audience and care setting to find the right training.',
  'Statistiques du catalogue': 'Catalogue statistics',
  'Cours publics actifs': 'Active public courses',
  'Formations en vedette': 'Featured training',
  'Audiences ciblées': 'Target audiences',
  'Catalogue structuré': 'Structured catalogue',
  'Trouvez rapidement la formation adaptée à votre équipe': 'Quickly find the right training for your team',
  'Formations en santé, ressources humaines, sécurité, informatique, onboarding, conformité, modules cliniques, ressources documentaires et cours complets.': 'Healthcare, HR, safety, IT, onboarding, compliance, clinical modules, document resources and complete courses.',
  'Recherche': 'Search',
  'Titre, tag, audience, lecturer, topic...': 'Title, tag, audience, lecturer, topic...',
  'Type': 'Type',
  'Tous les types': 'All types',
  'Kind': 'Kind',
  'Tous les kinds': 'All kinds',
  'Langue': 'Language',
  'Toutes les langues': 'All languages',
  'Audience': 'Audience',
  'Toutes les audiences': 'All audiences',
  'Care setting': 'Care setting',
  'Tous les settings': 'All settings',
  'Trier par': 'Sort by',
  'Visuels d’abord': 'Images first',
  'Titre A-Z': 'Title A-Z',
  'Durée croissante': 'Duration ascending',
  'CE credit décroissant': 'CE credit descending',
  'Réinitialiser': 'Reset',
  'Cours en vedette': 'Featured courses',
  'Les modules les plus visibles': 'Most visible modules',
  'Voir le cours': 'View course',
  'Résultats': 'Results',
  'Ajouter au parcours': 'Add to pathway',
  'Chargement du catalogue...': 'Loading catalogue...',
  'Pour petites équipes': 'For small teams',
  'Le plus populaire': 'Most popular',
  'Multi-organisation': 'Multi-organization',
  'Commencer': 'Start',
  'Payer mensuellement': 'Pay monthly',
  'Payer annuellement': 'Pay yearly',
  'Redirection...': 'Redirecting...',
  'Paiement en ligne indisponible. Nous pouvons vous envoyer un lien sécurisé.': 'Online payment is unavailable. We can send you a secure payment link.',
  'Paiement reçu. Votre abonnement sera vérifié automatiquement.': 'Payment received. Your subscription will be verified automatically.',
  'Paiement annulé. Vous pouvez reprendre quand vous êtes prêt.': 'Payment cancelled. You can resume when you are ready.',
  'Réserver une démo': 'Book a demo',
  'Jusqu’à 25 apprenants': 'Up to 25 learners',
  'Jusqu’à 100 apprenants': 'Up to 100 learners',
  'Suivi des complétions': 'Completion tracking',
  'Quiz et évaluations de base': 'Basic quizzes and assessments',
  'Tous les outils Starter': 'All Starter tools',
  'Certificats et dossiers de preuve': 'Certificates and evidence records',
  'Vue manager avancée': 'Advanced manager view',
  'Relances et suivi renforcé': 'Reminders and stronger follow-up',
  'Parcours par rôle / équipe': 'Pathways by role / team',
  'Modules produit': 'Product modules',
  'Pilotage, conformité et traçabilité': 'Oversight, compliance and traceability',
  'Fonctionnalités Innovacare Training': 'Innovacare Training features',
  'Tout ce qu’il faut pour piloter la formation en santé avec rigueur': 'Everything needed to manage healthcare training with rigor',
  'Innovacare Training centralise l’assignation des cours, le suivi des apprenants, les évaluations, les certificats et la documentation pour offrir une expérience plus claire, plus moderne et plus traçable.': 'Innovacare Training centralizes course assignments, learner tracking, assessments, certificates and documentation for a clearer, more modern and more traceable experience.',
  'Retour accueil': 'Back home',
  'Explorer les modules': 'Explore modules',
  'Modules clés': 'Key modules',
  'Des briques fonctionnelles conçues pour les organisations de santé': 'Functional building blocks designed for healthcare organizations',
  'Chaque fonctionnalité renforce la standardisation, la visibilité et la préparation de vos équipes.': 'Each feature strengthens standardization, visibility and team readiness.',
  'Une logique simple, du contenu jusqu’à la preuve': 'A simple flow, from content to evidence',
  'Par rôle': 'By role',
  'Une plateforme utile pour les managers comme pour les apprenants': 'A useful platform for managers and learners',
  'Accès apprenant': 'Learner access',
  'Assignation intelligente des cours': 'Smart course assignment',
  'Attribuez des formations par rôle, équipe, organisation ou parcours métier.': 'Assign training by role, team, organization or job pathway.',
  'Assignation par poste ou département': 'Assignment by position or department',
  'Parcours obligatoires et optionnels': 'Required and optional pathways',
  'Vue claire des formations attribuées': 'Clear view of assigned training',
  'Suivi des apprenants': 'Learner tracking',
  'Visualisez la progression, les retards, les complétions et les écarts de conformité.': 'View progress, delays, completions and compliance gaps.',
  'Statuts en temps réel': 'Real-time statuses',
  'Relances des apprenants en retard': 'Reminders for delayed learners',
  'Meilleure visibilité manager': 'Better manager visibility',
  'Quiz, évaluations et validation': 'Quizzes, assessments and validation',
  'Renforcez l’acquisition des connaissances avec des évaluations structurées.': 'Strengthen knowledge acquisition with structured assessments.',
  'Offres & déploiement': 'Plans and deployment',
  'Plans pensés pour les équipes de santé': 'Plans designed for healthcare teams',
  'Des tarifs pensés pour la croissance de vos équipes': 'Pricing designed for your team’s growth',
  'Choisissez une formule adaptée à votre taille, votre niveau d’exigence et votre besoin de visibilité sur la formation.': 'Choose a plan that fits your size, standards and need for training visibility.',
  'Mensuel': 'Monthly',
  'Annuel': 'Yearly',
  'Changer le mode de facturation': 'Change billing mode',
  'Comparaison': 'Comparison',
  'Comparez les plans rapidement': 'Compare plans quickly',
  'Fonctionnalité': 'Feature',
  'Ce qui est inclus': 'What is included',
  'Chaque plan est construit pour la clarté et la traçabilité': 'Every plan is built for clarity and traceability',
  'Quel que soit le niveau choisi, Innovacare Training reste orienté onboarding structuré, suivi des apprenants et documentation des résultats.': 'Whatever plan you choose, Innovacare Training stays focused on structured onboarding, learner tracking and result documentation.',
  'Parcours structurés': 'Structured pathways',
  'Créez des expériences cohérentes pour l’intégration et la montée en compétence.': 'Create consistent experiences for onboarding and skill development.',
  'Conservez un historique clair des validations, quiz et complétions.': 'Keep a clear history of validations, quizzes and completions.',
  'Visibilité manager': 'Manager visibility',
  'Repérez rapidement les retards, les écarts et les besoins de relance.': 'Quickly identify delays, gaps and follow-up needs.',
  'Bibliothèque pédagogique': 'Learning library',
  'Centralisez politiques, procédures et contenus dans un espace organisé.': 'Centralize policies, procedures and content in an organized space.',
  'Plateforme de formation en santé': 'Healthcare training platform',
  'Produit': 'Product',
  'Catégories': 'Categories',
  'Comment ça marche': 'How it works',
  'Entreprise': 'Company',
  'Démo': 'Demo',
  'Confidentialité': 'Privacy',
  'Conditions': 'Terms',
  '© 2026 Innovacare Training. Tous droits réservés.': '© 2026 Innovacare Training. All rights reserved.',
  'Fermer': 'Close',
  'Voyons comment Innovacare Training peut s’adapter à votre structure': 'Let’s see how Innovacare Training can fit your organization',
  'Remplissez ce formulaire et votre lead sera enregistré dans Firestore.': 'Complete this form and your lead will be saved in Firestore.',
  'Nom complet': 'Full name',
  'Le nom est requis.': 'Name is required.',
  'Email professionnel': 'Work email',
  'L’email est requis.': 'Email is required.',
  'Email invalide.': 'Invalid email.',
  'Téléphone': 'Phone',
  'Organisation': 'Organization',
  'Champ requis.': 'Required field.',
  'Type d’organisation': 'Organization type',
  'Plan sélectionné': 'Selected plan',
  'Message': 'Message',
  'Le message est requis.': 'Message is required.',
  'Annuler': 'Cancel',
  'Envoyer la demande': 'Send request',
  'Autre structure de santé': 'Other healthcare organization',
  'Retour au catalogue': 'Back to catalogue',
  'Crédits CE': 'CE credits',
  'Audience cible': 'Target audience',
  'Prérequis': 'Prerequisites',
  'Conditions requises': 'Requirements',
  'Leçons': 'Lessons',
  'Minutes': 'Minutes',
  'Passage requis': 'Required pass score',
  'Chargement du cours...': 'Loading course...',
};

@Injectable({ providedIn: 'root' })
export class LanguageService {
  private readonly storage = inject(SafeStorageService);

  readonly language = signal<AppLanguage>(this.initialLanguage());
  readonly isFrench = computed(() => this.language() === 'fr');

  setLanguage(language: AppLanguage): void {
    this.language.set(language);
    this.storage.setItem(STORAGE_KEY, language);
  }

  t(key: string, params: TranslationParams = {}): string {
    const dictionary = TRANSLATIONS[this.language()];
    const fallback = TRANSLATIONS.en[key] ?? key;
    const template = dictionary[key] ?? fallback;

    return Object.entries(params).reduce(
      (value, [paramKey, paramValue]) => value.replaceAll(`{${paramKey}}`, String(paramValue)),
      template
    );
  }

  publicText(text: string, language: AppLanguage = this.language()): string {
    if (language !== 'en') return text;

    const trimmed = text.replace(/\s+/g, ' ').trim();
    if (!trimmed) return text;

    const translated = PUBLIC_TEXT_EN[trimmed] ?? this.translatePublicPattern(trimmed);
    if (!translated || translated === trimmed) return text;

    return text.replace(trimmed, translated);
  }

  private translatePublicPattern(text: string): string {
    const moduleCount = text.match(/^(\d+) modules disponibles$/);
    if (moduleCount) return `${moduleCount[1]} available modules`;

    const resultCount = text.match(/^(\d+) résultats visibles$/);
    if (resultCount) return `${resultCount[1]} visible results`;

    const courseCount = text.match(/^(\d+) cours trouvés$/);
    if (courseCount) return `${courseCount[1]} courses found`;

    const minutes = text.match(/^(\d+) min$/);
    if (minutes) return `${minutes[1]} min`;

    const lessons = text.match(/^(\d+) lessons$/);
    if (lessons) return `${lessons[1]} lessons`;

    const pass = text.match(/^(\d+)% pass$/);
    if (pass) return `${pass[1]}% pass`;

    return text;
  }

  private initialLanguage(): AppLanguage {
    const saved = this.storage.getItem(STORAGE_KEY)?.toLowerCase();
    return saved === 'fr' ? 'fr' : 'en';
  }
}
